---
version: '3'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password123
      PGPASSWORD: password123
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
